### ISSUE TITLE
Add shortening for long titles and author names

### ISSUE THREAD

**Issue by luk-str** [luk-str/Archive-Radio#5]
Add shortening for long titles that sometimes occur, so that they don't mess up the layout. Ideally there should be a fixed space for title / author display that always stays the same.

Potential solution might be to hide the overflow and add animation that slowly scrolls the title horizontally to reveal the full text (like in a car radio).

**Comment by Jwright707** [comment]
I'd like to tackle this issue. 😀

**Comment by Jwright707** [comment]
I'm curious, would you like the width to be more limited? This would allow for the overflow to be scrollable. Attached is an image for a long name and name of a song. 
![image](https://user-images.githubusercontent.com/40744027/103175860-14cd0300-4822-11eb-949f-9faf7152c151.png)

**Comment by luk-str** [comment]
@Jwright707 Yeah, good example, some of the titles are messed up and way too long. I'm thinking they should always stay about the same width as the album art and probably be limited to 1 line. The full title can then animate back and forth slowly within these boundaries.

**Comment by luk-str** [comment]
Just merged a working fix #9. Still space for improvement though :)

**Comment by luk-str** [comment]
Next step could be to find a way to make the scroll animation always have the same speed, no matter the length of the title.

Right now it's just set to 10 seconds so it moves very slowly on short titles and fast on long ones. Not optimal 🤔

**Comment by Jwright707** [comment]
Hey @luk-str , sounds good! I can take a look at trying to improve the scroll speed tomorrow 👍

**Comment by luk-str** [comment]
Awesome Joshua! 🖖
